# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensg', models.CharField(max_length=15)),
                ('entrez', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdr', models.FloatField()),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Function')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Gene')),
            ],
            options={
                'ordering': ['fdr'],
            },
        ),
        migrations.CreateModel(
            name='GeneName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='genefunction',
            name='predictior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Predictor'),
        ),
        migrations.AddField(
            model_name='function',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Ontology'),
        ),
    ]
