# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneName',
            new_name='GeneAlias',
        ),
        migrations.AddField(
            model_name='gene',
            name='name',
            field=models.CharField(default=' ', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
