# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0003_auto_20160303_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='keyword',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='ensg',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='genefunction',
            unique_together=set([('gene', 'function', 'predictior')]),
        ),
    ]
