# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0004_auto_20160303_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='prj_path',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
