# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0005_auto_20160303_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='prj_path',
        ),
    ]
