# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0006_remove_predictor_prj_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predictor',
            new_name='ExpressionSource',
        ),
    ]
