# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0007_auto_20160303_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genefunction',
            old_name='predictior',
            new_name='expression_source',
        ),
        migrations.AddField(
            model_name='expressionsource',
            name='internal_name',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='genefunction',
            unique_together=set([('gene', 'function', 'expression_source')]),
        ),
    ]
