# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0008_auto_20160303_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='genefunction',
            name='known',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
