# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0009_genefunction_known'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_source', models.ManyToManyField(to='funcpred.ExpressionSource')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Gene')),
                ('ontology', models.ManyToManyField(to='funcpred.Ontology')),
            ],
        ),
    ]
