# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0010_genesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotype', models.CharField(choices=[(b'lincRNA', b'lincRNA'), (b'other', b'other'), (b'protein_coding', b'protein_coding'), (b'antisense', b'antisense'), (b'pseudogene', b'pseudogene')], max_length=14)),
                ('expression_source', models.ManyToManyField(to='funcpred.ExpressionSource')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Function')),
            ],
        ),
    ]
