# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0011_functionsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionsearch',
            name='ontology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funcpred.Ontology'),
            preserve_default=False,
        ),
    ]
