# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0012_functionsearch_ontology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionsearch',
            name='biotype',
            field=models.CharField(blank=True, choices=[(b'lincRNA', b'lincRNA'), (b'other', b'other'), (b'protein_coding', b'protein_coding'), (b'antisense', b'antisense'), (b'pseudogene', b'pseudogene')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='functionsearch',
            name='ontology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcpred.Ontology'),
        ),
    ]
