# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0013_auto_20160307_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genesearch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcpred.Session'),
        ),
    ]
