# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0015_auto_20160404_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
