# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcpred', '0016_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscanRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Function')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcpred.Gene')),
            ],
        ),
    ]
