Disease_list_noIEA.txt:
	https://ctgb-hsr.slack.com/files/paolo.provero/F4XFYM56J/disease_list_noiea.txt

gene.txt:
	https://ctgb-hsr.slack.com/messages/C3ZQLA9GT/files/F4XFYM56J/$@

phenotype.txt:
	https://ctgb-hsr.slack.com/messages/C3ZQLA9GT/files/F4XFYM56J/$@

HPO_descr.txt:
	wget https://ctgb-hsr.slack.com/files/cittaro.davide/F56KDKGJU/hpo_descr.txt
