Disease_list_noIEA.txt:
	https://ctgb-hsr.slack.com/files/paolo.provero/F4XFYM56J/disease_list_noiea.txt

gene.txt:
	https://ctgb-hsr.slack.com/messages/C3ZQLA9GT/files/F4XFYM56J/$@

phenotype.txt:
	https://ctgb-hsr.slack.com/messages/C3ZQLA9GT/files/F4XFYM56J/$@
